### ISSUE TITLE
Can't load one of my wallets . Multibit classic ,reward 1 BTC

### ISSUE THREAD

**Issue by slowdayz** [keepkey/multibit#781]
Hello, today i've been transferring some btc between my multibit classic wallets , the moment i have created new wallet , my another wallet went down , and now i can't open it anymore . It's says : could not load wallet file , error message was null . I tried some tutorials , with different versions of multibit and wipe it , also another computer , bitcoin core , electrum , renaming , but seems nothing is working. was also created just today , and i have only original .wall .info files and data file ,it was not encrypted , i had not exported keys at that moment. Wallet have back up files , i manage to open only earliest one , and it showed my 1 of 2 btc address in that wallet , i was able to send out small fraction of what is in rest btc address of that wallet , i can't get opened. I have been reading all day and i see only option is decrypt private keys from wallet file. As wallet is not password protected it should be possible . Can anyone help me ?  I can reward 1 BTC if issue is solved.
Thank you And Best Regards

**Comment by slowdayz** [comment]
15:45:00.968 [main] INFO  org.multibit.MultiBit - Starting MultiBit at 28 Mar 2017 13:45:00 GMT
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.runtime.name = Java(TM) SE Runtime Environment
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.moduleName = C:\MultiBitClassicPortable0519\multibit-classic.exe
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.semaphoreName = Local\c:_multibitclassicportable0519_multibit-classic.exe0
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.boot.library.path = c:\multibitclassicportable0519\jre\bin
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.version = 24.80-b11
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.vendor = Oracle Corporation
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vendor.url = http://java.oracle.com/
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.consoleCodepage = cp0
15:45:00.968 [main] DEBUG org.multibit.MultiBit - path.separator = ;
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.name = Java HotSpot(TM) Client VM
15:45:00.968 [main] DEBUG org.multibit.MultiBit - file.encoding.pkg = sun.io
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.country = US
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.script = 
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.os.patch.level = Service Pack 1
15:45:00.968 [main] DEBUG org.multibit.MultiBit - install4j.exeDir = C:\MultiBitClassicPortable0519\
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.specification.name = Java Virtual Machine Specification
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.dir = C:\MultiBitClassicPortable0519
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.runtime.version = 1.7.0_80-b15
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.endorsed.dirs = c:\multibitclassicportable0519\jre\lib\endorsed
15:45:00.968 [main] DEBUG org.multibit.MultiBit - os.arch = x86
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.io.tmpdir = C:\Users\Alien\AppData\Local\Temp\
15:45:00.968 [main] DEBUG org.multibit.MultiBit - line.separator =
 
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.specification.vendor = Oracle Corporation
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.variant = 
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.tempDir = 
15:45:00.968 [main] DEBUG org.multibit.MultiBit - os.name = Windows 7
15:45:00.968 [main] DEBUG org.multibit.MultiBit - apple.laf.useScreenMenuBar = true
15:45:00.968 [main] DEBUG org.multibit.MultiBit - proxySet = false
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.jnu.encoding = Cp1252
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.library.path = C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Lenovo;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;c:\multibitclassicportable0519\jre\bin
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.awt.enableExtraMouseButtons = true
15:45:00.968 [main] DEBUG org.multibit.MultiBit - install4j.launcherId = 24
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.specification.name = Java Platform API Specification
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.class.version = 51.0
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.management.compiler = HotSpot Client Compiler
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.isInstall4j = true
15:45:00.968 [main] DEBUG org.multibit.MultiBit - os.version = 6.1
15:45:00.968 [main] DEBUG org.multibit.MultiBit - install4j.swt = false
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.home = C:\Users\Alien
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.timezone = Europe/Paris
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.awt.printerjob = sun.awt.windows.WPrinterJob
15:45:00.968 [main] DEBUG org.multibit.MultiBit - file.encoding = Cp1252
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.specification.version = 1.7
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.class.path = C:\MultiBitClassicPortable0519\.install4j\i4jruntime.jar;C:\MultiBitClassicPortable0519\.\multibit-exe.jar;C:\MultiBitClassicPortable0519\.install4j\user.jar;C:\MultiBitClassicPortable0519\jre\lib\deploy.jar;C:\MultiBitClassicPortable0519\jre\lib\plugin.jar
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.name = Alien
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.specification.version = 1.7
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.java.command = C:\MultiBitClassicPortable0519\multibit-classic.exe
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.home = c:\multibitclassicportable0519\jre
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.arch.data.model = 32
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.launchName = C:\MultiBitClassicPortable0519\multibit-classic.exe
15:45:00.968 [main] DEBUG org.multibit.MultiBit - user.language = en
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.specification.vendor = Oracle Corporation
15:45:00.968 [main] DEBUG org.multibit.MultiBit - awt.toolkit = sun.awt.windows.WToolkit
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vm.info = mixed mode, sharing
15:45:00.968 [main] DEBUG org.multibit.MultiBit - exe4j.unextractedPosition = 0
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.version = 1.7.0_80
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.ext.dirs = c:\multibitclassicportable0519\jre\lib\ext;C:\Windows\Sun\Java\lib\ext
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.boot.class.path = c:\multibitclassicportable0519\jre\lib\resources.jar;c:\multibitclassicportable0519\jre\lib\rt.jar;c:\multibitclassicportable0519\jre\lib\sunrsasign.jar;c:\multibitclassicportable0519\jre\lib\jsse.jar;c:\multibitclassicportable0519\jre\lib\jce.jar;c:\multibitclassicportable0519\jre\lib\charsets.jar;c:\multibitclassicportable0519\jre\lib\jfr.jar;c:\multibitclassicportable0519\jre\classes
15:45:00.968 [main] DEBUG org.multibit.MultiBit - install4j.appDir = C:\MultiBitClassicPortable0519\
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vendor = Oracle Corporation
15:45:00.968 [main] DEBUG org.multibit.MultiBit - file.separator = \
15:45:00.968 [main] DEBUG org.multibit.MultiBit - java.vendor.url.bug = http://bugreport.sun.com/bugreport/
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.io.unicode.encoding = UnicodeLittle
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.cpu.endian = little
15:45:00.968 [main] DEBUG org.multibit.MultiBit - install4j.systemLanguage = en
15:45:00.968 [main] DEBUG org.multibit.MultiBit - install4j.keepLog = true
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.desktop = windows
15:45:00.968 [main] DEBUG org.multibit.MultiBit - sun.cpu.isalist = pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
15:45:00.968 [main] INFO  o.m.ApplicationDataDirectoryLocator - Application data directory.1 = ''
15:45:00.983 [main] INFO  org.multibit.MultiBit - Configuring native event handling
15:45:00.983 [main] INFO  org.multibit.MultiBit - Checking to see if this is the primary MultiBit instance
15:45:00.983 [main] DEBUG o.m.ApplicationInstanceManager - Listening for application instances on socket 8331
15:45:00.983 [main] DEBUG org.multibit.MultiBit - userLanguageCode = en
15:45:00.983 [main] DEBUG org.multibit.MultiBit - MultiBit version = 0.5.19
15:45:00.983 [main] DEBUG org.multibit.MultiBit - Creating model
15:45:00.983 [main] DEBUG org.multibit.model.BaseModel - Initial view from properties file is 'SHOW_IMPORT_PRIVATE_KEYS_VIEW'
15:45:01.014 [main] DEBUG org.multibit.MultiBit - Setting look and feel
15:45:01.014 [main] DEBUG o.m.v.swing.ColorAndFontConstants - labelBackground = 240 240 240
15:45:01.014 [main] DEBUG o.m.v.swing.ColorAndFontConstants - labelForeground = 0 0 0
15:45:01.014 [main] DEBUG org.multibit.MultiBit - Creating user interface with initial view : SHOW_IMPORT_PRIVATE_KEYS_VIEW
15:45:01.030 [main] DEBUG o.m.v.swing.ColorAndFontConstants - labelBackground = 240 240 240
15:45:01.030 [main] DEBUG o.m.v.swing.ColorAndFontConstants - labelForeground = 0 0 0
15:45:01.248 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - exchange is null ... creating exchange ... (isFirstExchange = true)
15:45:01.248 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - shortExchangeName is null, defaulting to Bitstamp
15:45:01.248 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - creating exchange from exchangeShortname  = Bitstamp
15:45:01.248 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = ''
15:45:01.248 [main] DEBUG o.m.viewsystem.swing.MultiBitFrame - Displaying view 'SHOW_IMPORT_PRIVATE_KEYS_VIEW'
15:45:01.389 [main] DEBUG org.multibit.MultiBit - Registering with controller
15:45:01.389 [main] DEBUG org.multibit.MultiBit - The user data directory is "".
15:45:01.389 [main] DEBUG org.multibit.MultiBit - The installation directory is "C:\MultiBitClassicPortable0519".
15:45:01.389 [main] DEBUG org.multibit.MultiBit - Creating Bitcoin service
15:45:01.389 [AWT-EventQueue-0] DEBUG o.m.v.swing.MultiBitTabbedPane - Set selected index = 3
15:45:01.436 [main] DEBUG org.multibit.network.MultiBitService - Network parameters = com.google.bitcoin.params.MainNetParams@9d1d82f2
15:45:01.436 [main] DEBUG org.multibit.network.MultiBitService - Loading/ creating blockstore ...
15:45:01.436 [main] DEBUG org.multibit.network.MultiBitService - filePrefix = multibit
15:45:01.436 [main] INFO  o.m.ApplicationDataDirectoryLocator - Application data directory.1 = ''
15:45:01.436 [main] DEBUG org.multibit.network.MultiBitService - Installed checkpoints file = 'C:\MultiBitClassicPortable0519\multibit.checkpoints'.
15:45:01.436 [main] DEBUG org.multibit.network.MultiBitService - Using user data checkpoints file as it is longer/same size as installed checkpoints - 17493 bytes versus 17493 bytes.
15:45:01.436 [main] DEBUG org.multibit.network.MultiBitService - Opening / Creating SPV block store 'multibit.spvchain' from disk
15:45:01.482 [main] DEBUG org.multibit.network.MultiBitService - Blockstore is 'com.google.bitcoin.store.SPVBlockStore@1aa7bb6'
15:45:01.482 [main] DEBUG org.multibit.network.MultiBitService - Creating blockchain ...
15:45:01.529 [main] DEBUG org.multibit.network.MultiBitService - Created [Suspicious link removed].google.bitcoin.core.MultiBitBlockChain@be458b' with height 459337
15:45:01.529 [main] DEBUG org.multibit.network.MultiBitService - Creating peergroup ...
15:45:01.560 [main] DEBUG org.multibit.network.MultiBitService - Created peergroup 'MultiBitPeerGroup [NEW]'
15:45:01.560 [main] DEBUG org.multibit.network.MultiBitService - Starting peergroup ...
15:45:01.560 [main] DEBUG org.multibit.network.MultiBitService - Started peergroup.
15:45:01.576 [main] DEBUG org.multibit.MultiBit - Locating wallets
15:45:01.576 [main] DEBUG org.multibit.MultiBit - When loading early wallets, there were 1
15:45:01.576 [main] DEBUG org.multibit.MultiBit - When loading protobuf3 wallets, there were 0
15:45:01.576 [main] DEBUG org.multibit.MultiBit - When loading the wallet orders, there were 1
15:45:01.576 [main] DEBUG org.multibit.MultiBit - Loading wallet from 'C:\MultiBitClassicPortable0519\mano.wallet'
15:45:01.576 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - marketDataService = com.xeiam.xchange.bitstamp.service.polling.BitstampPollingMarketDataService@cc5d4b
15:45:01.576 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - exchangeSymbols = [BTC/USD]
15:45:01.576 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - Getting ticker for BTC USD
15:45:01.576 [main] DEBUG o.m.model.bitcoin.WalletInfoData - The wallet version in the constructor was '3'. In the wallet info file it was '2'. Using the latter.
15:45:01.763 [Timer-4] DEBUG o.m.model.exchange.ConnectHttps - checkServerTrusted authType = ECDHE_RSA
15:45:01.872 [main] DEBUG org.multibit.MultiBit - Cleaning wallet 'C:\MultiBitClassicPortable0519\mano.wallet' of spam ...
15:45:01.872 [main] DEBUG org.multibit.MultiBit - done.
15:45:01.888 [main] DEBUG o.m.v.swing.MultiBitTabbedPane - Set selected index = 0
15:45:01.888 [main] DEBUG org.multibit.MultiBit - Checking for Bitcoin URI on command line
15:45:01.888 [main] DEBUG org.multibit.MultiBit - No Bitcoin URI provided as an argument
15:45:01.888 [main] DEBUG o.m.c.bitcoin.BitcoinController - handleOpenURI.2 called and rawBitcoinURIString ='null'
15:45:01.888 [main] DEBUG o.m.c.bitcoin.BitcoinController - No Bitcoin URI found to handle
15:45:01.888 [main] DEBUG org.multibit.MultiBit - Downloading blockchain
15:45:01.888 [main] DEBUG org.multibit.MultiBit - The current chain height is 459337
15:45:01.888 [main] DEBUG org.multibit.MultiBit - For wallet 'C:\MultiBitClassicPortable0519\mano.wallet the lastBlockSeenHeight was 459337
15:45:01.888 [main] DEBUG org.multibit.MultiBit - needToSync = false
15:45:01.904 [SwingWorker-pool-3-thread-1] DEBUG org.multibit.network.ReplayManager - Downloading blockchain - regularDownloadIsRunning = true
15:45:01.950 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Synchronising with network...'
15:45:01.966 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - Got ticker for BTC USD
15:45:01.966 [Timer-4] DEBUG o.multibit.exchange.TickerTimerTask - Exchange = Bitstamp
15:45:02.184 [NioClientManager] DEBUG org.multibit.network.ReplayManager - ReplayTask with UUID null has completed.
15:45:02.184 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Synchronised with network.'
15:45:02.184 [NioClientManager] DEBUG org.multibit.network.ReplayManager - ReplayTask with UUID null has completed.
15:45:02.184 [bitcoinj user thread] DEBUG org.multibit.network.ReplayManager - Download has completed (in ReplayManager) - regularDownloadIsRunning = false
15:45:02.184 [bitcoinj user thread] DEBUG org.multibit.network.ReplayManager - Download has completed (in ReplayManager) - regularDownloadIsRunning = false
15:45:02.184 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Synchronised with network.'
15:45:02.294 [NioClientManager] DEBUG org.multibit.network.ReplayManager - ReplayTask with UUID null has completed.
15:45:02.294 [bitcoinj user thread] DEBUG org.multibit.network.ReplayManager - Download has completed (in ReplayManager) - regularDownloadIsRunning = false
15:45:02.294 [bitcoinj user thread] DEBUG org.multibit.network.ReplayManager - Download has completed (in ReplayManager) - regularDownloadIsRunning = false
15:45:02.294 [NioClientManager] DEBUG org.multibit.network.ReplayManager - ReplayTask with UUID null has completed.
15:45:02.294 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Synchronised with network.'
15:45:02.294 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Synchronised with network.'
15:45:08.393 [AWT-EventQueue-0] DEBUG o.m.v.swing.action.OpenWalletAction - Executing open of wallet 'C:\MultiBitClassicPortable0519\003.wallet'.
15:45:08.393 [SwingWorker-pool-3-thread-2] DEBUG o.m.v.swing.action.OpenWalletAction - Opening wallet 'C:\MultiBitClassicPortable0519\003.wallet'.
15:45:08.393 [SwingWorker-pool-3-thread-2] DEBUG o.m.model.bitcoin.WalletInfoData - The wallet version in the constructor was '3'. In the wallet info file it was '2'. Using the latter.
com.google.bitcoin.store.UnreadableWalletException: Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
   at org.multibit.store.MultiBitWalletProtobufSerializer.readTransaction(MultiBitWalletProtobufSerializer.java:624)
   at org.multibit.store.MultiBitWalletProtobufSerializer.readWallet(MultiBitWalletProtobufSerializer.java:460)
   at org.multibit.store.MultiBitWalletProtobufSerializer.readWallet(MultiBitWalletProtobufSerializer.java:392)
   at com.google.bitcoin.core.Wallet.loadFromFileStream(Wallet.java:572)
   at org.multibit.file.FileHandler.loadFromFile(FileHandler.java:115)
   at org.multibit.network.MultiBitService.addWalletFromFilename(MultiBitService.java:410)
   at org.multibit.controller.bitcoin.BitcoinController.addWalletFromFilename(BitcoinController.java:137)
   at org.multibit.viewsystem.swing.action.OpenWalletAction$1.doInBackground(OpenWalletAction.java:288)
   at org.multibit.viewsystem.swing.action.OpenWalletAction$1.doInBackground(OpenWalletAction.java:276)
   at javax.swing.SwingWorker$1.call(Unknown Source)
   at java.util.concurrent.FutureTask.run(Unknown Source)
   at javax.swing.SwingWorker.run(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   at java.lang.Thread.run(Unknown Source)
15:45:08.409 [SwingWorker-pool-3-thread-2] ERROR org.multibit.file.FileHandler - com.google.bitcoin.store.UnreadableWalletException Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
15:45:08.409 [SwingWorker-pool-3-thread-2] DEBUG org.multibit.file.BackupManager - For wallet 'C:\MultiBitClassicPortable0519\003.wallet' the rolling backup file was 'C:\Users\Alien\Desktop\MultiBit\003-data\rolling-backup\003-20170328100621.wallet' and the best encrypted/ unencrypted backup was 'C:\MultiBitClassicPortable0519\003-data\wallet-unenc-backup\003-20170328082816.wallet'
com.google.bitcoin.store.UnreadableWalletException: Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
   at org.multibit.store.MultiBitWalletProtobufSerializer.readTransaction(MultiBitWalletProtobufSerializer.java:624)
   at org.multibit.store.MultiBitWalletProtobufSerializer.readWallet(MultiBitWalletProtobufSerializer.java:460)
   at org.multibit.store.MultiBitWalletProtobufSerializer.readWallet(MultiBitWalletProtobufSerializer.java:392)
   at com.google.bitcoin.core.Wallet.loadFromFileStream(Wallet.java:572)
   at org.multibit.file.FileHandler.loadFromFile(FileHandler.java:149)
   at org.multibit.network.MultiBitService.addWalletFromFilename(MultiBitService.java:410)
   at org.multibit.controller.bitcoin.BitcoinController.addWalletFromFilename(BitcoinController.java:137)
   at org.multibit.viewsystem.swing.action.OpenWalletAction$1.doInBackground(OpenWalletAction.java:288)
   at org.multibit.viewsystem.swing.action.OpenWalletAction$1.doInBackground(OpenWalletAction.java:276)
   at javax.swing.SwingWorker$1.call(Unknown Source)
   at java.util.concurrent.FutureTask.run(Unknown Source)
   at javax.swing.SwingWorker.run(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   at java.lang.Thread.run(Unknown Source)
15:45:08.409 [SwingWorker-pool-3-thread-2] ERROR org.multibit.file.FileHandler - com.google.bitcoin.store.UnreadableWalletException Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
com.google.bitcoin.store.UnreadableWalletException: Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
   at org.multibit.store.MultiBitWalletProtobufSerializer.readTransaction(MultiBitWalletProtobufSerializer.java:624)
   at org.multibit.store.MultiBitWalletProtobufSerializer.readWallet(MultiBitWalletProtobufSerializer.java:460)
   at org.multibit.store.MultiBitWalletProtobufSerializer.readWallet(MultiBitWalletProtobufSerializer.java:392)
   at com.google.bitcoin.core.Wallet.loadFromFileStream(Wallet.java:572)
   at org.multibit.file.FileHandler.loadFromFile(FileHandler.java:149)
   at org.multibit.network.MultiBitService.addWalletFromFilename(MultiBitService.java:410)
   at org.multibit.controller.bitcoin.BitcoinController.addWalletFromFilename(BitcoinController.java:137)
   at org.multibit.viewsystem.swing.action.OpenWalletAction$1.doInBackground(OpenWalletAction.java:288)
   at org.multibit.viewsystem.swing.action.OpenWalletAction$1.doInBackground(OpenWalletAction.java:276)
   at javax.swing.SwingWorker$1.call(Unknown Source)
   at java.util.concurrent.FutureTask.run(Unknown Source)
   at javax.swing.SwingWorker.run(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   at java.lang.Thread.run(Unknown Source)
15:45:08.409 [SwingWorker-pool-3-thread-2] ERROR org.multibit.file.FileHandler - com.google.bitcoin.store.UnreadableWalletException Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
15:45:08.409 [SwingWorker-pool-3-thread-2] DEBUG o.m.v.swing.action.OpenWalletAction - Setting active wallet for file 'C:\MultiBitClassicPortable0519\003.wallet'.
15:45:08.409 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Unable to load wallet "C:\MultiBitClassicPortable0519\003.wallet" or backups. See help on "Wallet Backups" for more details.
The error was "com.google.bitcoin.store.UnreadableWalletException Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
com.google.bitcoin.store.UnreadableWalletException Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871
com.google.bitcoin.store.UnreadableWalletException Transaction did not deserialize completely: 663d1793aa8189fa6dfd73c4230c40fd16462daee44d0667bf90b62ff9ee48a1 vs e9f931f019058179b910081354500b5d3613253ac60c25cf288ba2355b854871".'
15:45:08.409 [SwingWorker-pool-3-thread-2] DEBUG o.m.v.swing.action.OpenWalletAction - Writing user preferences. . .
15:45:08.409 [SwingWorker-pool-3-thread-2] DEBUG o.m.v.swing.action.OpenWalletAction - User preferences with new wallet written successfully
15:45:08.440 [AWT-EventQueue-0] ERROR o.m.v.swing.action.OpenWalletAction - Could not load the wallet file "C:\MultiBitClassicPortable0519\003.wallet".
The error message was "null"
15:45:08.440 [AWT-EventQueue-0] DEBUG o.m.viewsystem.swing.StatusBar - StatusBar label = 'Could not load the wallet file "C:\MultiBitClassicPortable0519\003.wallet".
The error message was "null"'

**Comment by brohemath** [comment]
you are not the only one having problems with classic right now, If I find the solution I will hit you back, don't need the reward got 10G held up right now in this wallet haha
brohem

**Comment by Spratan** [comment]
I had the same problem 2 months ago and I recovered my btc.
I need to check again. Have you found the solution since your post?

**Comment by brohemath** [comment]
My solution was to load multibit on another computer and import the wallet keys to that computer.  Was able to get most of the wallets to load.  I found a solution somewhere else to said you needed to delete an sv file when you get that corruption report but they don't tell you where it is! lol  a file path would have been nice.

**Comment by terry1328** [comment]
Hello, did u manage to fix it?

**Comment by doge2021** [comment]
> Hello, today i've been transferring some btc between my multibit classic wallets , the moment i have created new wallet , my another wallet went down , and now i can't open it anymore . It's says : could not load wallet file , error message was null . I tried some tutorials , with different versions of multibit and wipe it , also another computer , bitcoin core , electrum , renaming , but seems nothing is working. was also created just today , and i have only original .wall .info files and data file ,it was not encrypted , i had not exported keys at that moment. Wallet have back up files , i manage to open only earliest one , and it showed my 1 of 2 btc address in that wallet , i was able to send out small fraction of what is in rest btc address of that wallet , i can't get opened. I have been reading all day and i see only option is decrypt private keys from wallet file. As wallet is not password protected it should be possible . Can anyone help me ? I can reward 1 BTC if issue is solved. Thank you And Best Regards

do you recovered it, it maybe caused by bug of multibit
https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/

**Comment by KONK777** [comment]
Nothing is impossible for me. Still having a problem?
Are you working on Windows or Linux?

**Comment by KONK777** [comment]
> > Hello, today i've been transferring some btc between my multibit classic wallets , the moment i have created new wallet , my another wallet went down , and now i can't open it anymore . It's says : could not load wallet file , error message was null . I tried some tutorials , with different versions of multibit and wipe it , also another computer , bitcoin core , electrum , renaming , but seems nothing is working. was also created just today , and i have only original .wall .info files and data file ,it was not encrypted , i had not exported keys at that moment. Wallet have back up files , i manage to open only earliest one , and it showed my 1 of 2 btc address in that wallet , i was able to send out small fraction of what is in rest btc address of that wallet , i can't get opened. I have been reading all day and i see only option is decrypt private keys from wallet file. As wallet is not password protected it should be possible . Can anyone help me ? I can reward 1 BTC if issue is solved. Thank you And Best Regards
> 
> do you recovered it, it maybe caused by bug of multibit https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/

Nothing is impossible for me. Still having a problem?
Are you working on Windows or Linux?

**Comment by KONK777** [comment]
> Hello, today i've been transferring some btc between my multibit classic wallets , the moment i have created new wallet , my another wallet went down , and now i can't open it anymore . It's says : could not load wallet file , error message was null . I tried some tutorials , with different versions of multibit and wipe it , also another computer , bitcoin core , electrum , renaming , but seems nothing is working. was also created just today , and i have only original .wall .info files and data file ,it was not encrypted , i had not exported keys at that moment. Wallet have back up files , i manage to open only earliest one , and it showed my 1 of 2 btc address in that wallet , i was able to send out small fraction of what is in rest btc address of that wallet , i can't get opened. I have been reading all day and i see only option is decrypt private keys from wallet file. As wallet is not password protected it should be possible . Can anyone help me ? I can reward 1 BTC if issue is solved. Thank you And Best Regards

Nothing is impossible for me. Still having a problem?
Are you working on Windows or Linux?

**Comment by KONK777** [comment]
> Hello, today i've been transferring some btc between my multibit classic wallets , the moment i have created new wallet , my another wallet went down , and now i can't open it anymore . It's says : could not load wallet file , error message was null . I tried some tutorials , with different versions of multibit and wipe it , also another computer , bitcoin core , electrum , renaming , but seems nothing is working. was also created just today , and i have only original .wall .info files and data file ,it was not encrypted , i had not exported keys at that moment. Wallet have back up files , i manage to open only earliest one , and it showed my 1 of 2 btc address in that wallet , i was able to send out small fraction of what is in rest btc address of that wallet , i can't get opened. I have been reading all day and i see only option is decrypt private keys from wallet file. As wallet is not password protected it should be possible . Can anyone help me ? I can reward 1 BTC if issue is solved. Thank you And Best Regards

Nothing is impossible for me. Still having a problem?

**Comment by doge2021** [comment]
> Hello, today i've been transferring some btc between my multibit classic wallets , the moment i have created new wallet , my another wallet went down , and now i can't open it anymore . It's says : could not load wallet file , error message was null . I tried some tutorials , with different versions of multibit and wipe it , also another computer , bitcoin core , electrum , renaming , but seems nothing is working. was also created just today , and i have only original .wall .info files and data file ,it was not encrypted , i had not exported keys at that moment. Wallet have back up files , i manage to open only earliest one , and it showed my 1 of 2 btc address in that wallet , i was able to send out small fraction of what is in rest btc address of that wallet , i can't get opened. I have been reading all day and i see only option is decrypt private keys from wallet file. As wallet is not password protected it should be possible . Can anyone help me ? I can reward 1 BTC if issue is solved. Thank you And Best Regards

https://btc2doge.com/ can help if you still have the files
